language: python
sudo: required
dist: trusty

branches:
  only:
    - master

install:
  - pip install -r requirements.txt  -t .
  - pip install pep8

script:
  - pep8 run.py
  - python -m unittest discover -s test

before_deploy:
  - zip -r squash.zip *

deploy:
  provider: lambda
  access_key_id: $access_key_id 
  secret_access_key: $secret_access_key
  function_name: pidorbot
  role: arn:aws:iam::879151756208:role/lambda
  handler_name: lambda_handler
  module_name: run
  zip: squash.zip
  runtime: python3.6
  publish: true
  on:
    branch: master
